### PR TITLE
fix the title

### LINKED ISSUE #14: I want to change the title which is not looking same as amazon original website.

### PR DESCRIPTION
**Pull request by SAYAN-DAN**
Here I modified the title which did not look good before the changes but after the changes, it looks like the original website. Below I give a screenshot of what I modify.

After the changes -

96585e02-d3d0-4756-b3ef-f43b3a236356

fixes #14

### CODE REVIEW

**Comment by Pritanshu69** [comment]
Dear @SAYAN-DAN the feature you've added is not working. And you've again commited into the branch which is not expected so I am closing your PR.

**Comment by Debaditya-Som** [comment]
@SAYAN-DAN I have mention it to you several times not to give PR to the main branch give it to the test branch instead as it will result in merge conflict 

image

**Comment by SAYAN-DAN** [comment]
I create a new branch and push it on the new branch. so what is the problem I don't understand.

**Comment by SAYAN-DAN** [comment]
> Dear @SAYAN-DAN the feature you've added is not working. And you've again committed to the branch which is not expected so I am closing your PR.

why my feature is not working I don't understand.

**Comment by SAYAN-DAN** [comment]
Please guide me on how to solve this problem.

**Pull request closed without merging**
